packages:
  -  "packages/utils"
  # - "packages/schema-type"
  # - "packages/solecs"
  - "packages/store"
  - "packages/world"
  - "packages/cli"
  - "packages/recs"
  - "packages/react"
  - "packages/phaserx"
  - "packages/network"
  - "packages/std-contracts"
  - "packages/std-client"
  - "packages/ecs-browser"
  - "packages/services"
  - "packages/noise"
  - "packages/create-mud"
